org.gradle.jvmargs=-Xmx3G
minecraft_version=1.18.2
archives_base_name=BedrockTools
mod_id=bedrocktools76
mod_name=BedrockTools
mod_version=1.0.8
maven_group=net.pitan76

# https://fabricmc.net/develop/
fabric_loader_version=0.18.6
fabric_api_version=0.76.0+1.18.2
yarn_mappings=1.18.2+build.4

# https://files.minecraftforge.net/
forge_version=1.18.2-40.2.10

# https://www.curseforge.com/minecraft/mc-mods/mcpitanlib
mcpitanlib_version=1.18.2:3.6.5
mcpitanlib_checker_version=1.0.4

# https://www.curseforge.com/minecraft/mc-mods/architectury-api
architectury_version=4.11.93

changelog=Support for 26.1.2
